name = "JuliaNumerical"
uuid = "e87ad218-e2a0-4367-bcd9-5b669cb95841"
authors = ["Seasawher <tellagoodstory@icloud.com>"]
version = "0.1.0"

[deps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
